#!/usr/bin/env python3
import subprocess
import glob
import os
import pytraj
from rdkit import Chem
from rdkit.Chem import Draw
from openbabel import openbabel

def PDBtoSMI(pdb):
    smi_file = pdb.replace(".pdb",".smi")
    if not glob.glob(smi_file):
        obConversion = openbabel.OBConversion()
        obConversion.SetInAndOutFormats("pdb", "smi")
        mol = openbabel.OBMol()
        obConversion.ReadFile(mol, pdb)
        obConversion.WriteFile(mol, smi_file)
    f = open(smi_file)
    smiles = f.read()
    f.close()
    return smiles.split()[0]

def Generate2DImage(smiles,image):
    Draw.MolToFile(Chem.MolFromSmiles(smiles), image, size=(1268,720))
    return

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-p","--pdb",dest="pdb",required=True,help="path/to/file.pdb")
    parser.add_argument("-o","--output",dest="output",required=True,help="output_filename.png")
    args = parser.parse_args()
    smiles = PDBtoSMI(args.pdb)
    Generate2DImage(smiles, args.output)
    
    
