#!/usr/bin/env python3
import subprocess
import glob
import os
import pytraj
from rdkit import Chem
from rdkit.Chem import Draw
from openbabel import openbabel

def Generate2DImage(smiles,image):
    Draw.MolToFile(Chem.MolFromSmiles(smiles), image, size=(1268,720))
    return

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-s","--smiles",dest="smiles",required=True,help="path/to/file.pdb")
    parser.add_argument("-o","--output",dest="output",required=True,help="output_filename.png")
    args = parser.parse_args()
    Generate2DImage(args.smiles, args.output)
